# Generated by Django 3.1 on 2020-08-28 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('contact', models.IntegerField()),
                ('matricnumber', models.IntegerField()),
                ('internumber', models.IntegerField()),
                ('bachelorcgpa', models.FloatField()),
            ],
        ),
    ]
