# Generated by Django 3.1 on 2020-08-31 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addcv', '0003_auto_20200831_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='picture',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
